services:
  # 開發環境應用程式
  app-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: library-app-dev
    # restart: always
    volumes:
      - .:/app  # 掛載程式碼目錄
      - maven-cache:/root/.m2  # 掛載Maven快取
    ports:
      - "8080:8080"  # 應用程式端口
      - "5005:5005"  # 除錯端口
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/library
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - library-network

  # PostgreSQL資料庫
  postgres:
    image: postgres:latest
    container_name: library-postgres
    # restart: always
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    # 移除端口映射，只在容器內部訪問
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # - ./database_schema.sql:/docker-entrypoint-initdb.d/init.sql  # Manual initialization
    networks:
      - library-network

  # pgAdmin (可選，資料庫管理工具)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: library-pgadmin
    # restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@library.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - library-network

volumes:
  maven-cache:  # Maven依賴快取
  postgres-data:  # PostgreSQL資料

networks:
  library-network:
    driver: bridge
