services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: library-app
    # restart: always
    volumes:
      - .:/app 
      - maven-cache:/root/.m2  # Mount Maven cache
    ports:
      - "8080:8080"  # Application port
      - "5005:5005"  # Debug port
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/library
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - library-network


  postgres:
    image: postgres:latest
    container_name: library-postgres
    # restart: always
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    # Remove port mapping, only accessible within container
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # - ./database_schema.sql:/docker-entrypoint-initdb.d/init.sql  # Manual initialization
    networks:
      - library-network


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: library-pgadmin
    # restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@library.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - library-network

volumes:
  maven-cache:  # Maven dependency cache
  postgres-data:  # PostgreSQL data

networks:
  library-network:
    driver: bridge
